#!/bin/zsh

# Autohide the dock
defaults write com.apple.Dock autohide 1

# Set the icon size of Dock items
defaults write com.apple.Dock tilesize -int 50

# Disable press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Disable automatic capitalization as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Show hidden files
defaults write com.apple.finder AppleShowAllFiles YES

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Enables secondary click
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseButtonMode TwoButton

# Enables battery percentage
defaults write com.apple.menuextra.battery ShowPercent YES

#Show full date
defaults write com.apple.menuextra.clock "DateFormat" 'EEE d MMM HH:mm'

# Disable font smoothing
# defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
defaults write -g CGFontRenderingFontSmoothingDisabled -bool YES

# Enable subpixel font rendering on non-Apple LCDs
# https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
defaults write NSGlobalDomain AppleFontSmoothing -int 1

# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/dotfiles/iterm"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Lock the Dock size
killall Dock
killall SystemUIServer